### PR TITLE
Leaks

### PR DESCRIPTION
**Pull request by b2mdevelopment**
Check for connectivity before try to read message
put any cursor within try/finally block to ensure closing it
move blackout files into it's own package
modify pre-commit hooks to error in case of lint error
show ryena coverage

### CODE REVIEW

**Comment by lazywithclass** [comment]
There's more than just fixing leaks, I would've preferred  two PRs, but I'm happy with this.

Ok

**Comment by CharlesGarth** [comment]
looks good! :+1:

**Comment by aflugge** [comment]
Looks ok to me.

**Comment by lazywithclass** [comment]
@Youhana-Hana where are you using `resetCellularDataBlackout` and why do we need it?

**Comment by b2mdevelopment** [comment]
@lazywithclass there were many tests that randomly failing due to the test orders that might set blackout.
I needed this method to ensure that no previously setting for blackout. then I used it when config file changed in elemez and cellular blackout removed.

@Youhana-Hana

**Pull request merged**
